apiVersion: v1
kind: Service
metadata:
  name: {{ include "diriyah-brain-ai.fullname" . }}
  labels:
    {{- include "diriyah-brain-ai.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type | default "ClusterIP" }}
  ports:
    - port: {{ .Values.service.port | default 80 }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "diriyah-brain-ai.selectorLabels" . | nindent 4 }}
